### ISSUE TITLE
Ship Build Archive - Phase 2

### ISSUE THREAD

**Issue by Admiralfeb** [Admiralfeb/usc-website#27]
This phase increases usability and shareability. 

- [ ] Query params for the build page #22 
- [ ] Build Archive full search/display all #25 
- [ ] Split build system off into a submodule #26
